### ISSUE TITLE
Question: Why not training heads?

### ISSUE THREAD

**Issue by fastlater** [mirzaevinom/data_science_bowl_2018#2]
Excellent repo. I liked the Interesting findings and the Unsuccessful approaches tried. Very useful for future experiments.
I still have one question. Why you didn't train the heads?
Many people recommended to train heads first, then a few times the 4+ (optional) and then train all. Why did your train all since the beginning. 
Is there any **reason** you skipped the train of heads part?

**Comment by mirzaevinom** [comment]
Thank you, @fastlater! In my experience, training all the weights together gave me better results. Maybe training heads first will give better results with some hyperparameter configuration.

**Comment by fastlater** [comment]
I see. Well, I am training using Adam now and I will see if training heads make or not improvements.
