### ISSUE TITLE
access to your weights.h5?

### ISSUE THREAD

**Issue by soroushr** [mirzaevinom/data_science_bowl_2018#4]
Thanks for sharing your code and the procedure with such detail Inom - I have learned a lot from it.

I was wondering if you have made your final trained weights publicly available? I am doing something similar to what you have done, but my training data is a bit small and that's why my results are not great (though they aren't terrible either).

My guess is that if I initiate my training using the weights you have obtained from this competition, I can get better results.

I don't know whether it is common to share the trained weights. If for any reason you cannot do it, I understand.
Thank you!

**Comment by mirzaevinom** [comment]
mirzaevinom

**Comment by mirzaevinom** [comment]
I am glad that you found the scripts helpful. I have added a link to weights in the readme file.

**Comment by leesky1c** [comment]
@mirzaevinom It seems that the link of downloading the weights became invalid...

**Comment by mirzaevinom** [comment]
Oops, I must have accidentally deleted whole folder. Please, try now 😃
